import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Sidebar from "./components/layout/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="antialiased">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background text-foreground flex justify-center items-center min-h-screen relative`}
      >
        {/* Google Fonts & Material Symbols */}
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700;800;900&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet" />

        <div className="fixed inset-0 islamic-pattern pointer-events-none z-0"></div>

        {/* Strict Mobile Frame: simulating an iPhone Pro Max width approx 430px */}
        <div className="w-full max-w-[430px] h-[95vh] rounded-[3rem] overflow-hidden shadow-2xl bg-black/90 flex flex-col relative border-[8px] border-neutral-800 ring-8 ring-black/50 z-10">
          {/* iOS-like Status Bar Area Placeholder */}
          <div className="w-full h-8 bg-background shrink-0 z-20" />

          <div className="flex-1 flex flex-col w-full overflow-hidden relative bg-background">
            <main className="flex-1 overflow-y-auto no-scrollbar scroll-smooth flex flex-col">
              {/* Top Header Row similar to design code.html */}
              <div className="flex items-center px-6 py-4 justify-between z-10 border-b border-primary/10">
                <div className="text-white flex size-14 shrink-0 items-center">
                  <span className="material-symbols-outlined text-primary scale-150">menu</span>
                </div>
                <h2 className="text-primary text-xl font-black leading-tight tracking-tight flex-1 text-center uppercase">EEIS PRAYER TIME TABLE</h2>
                <div className="flex w-14 items-center justify-end">
                  <button className="flex items-center justify-center text-white p-0">
                    <span className="material-symbols-outlined text-primary scale-150">notifications</span>
                  </button>
                </div>
              </div>

              {children}
            </main>

            {/* Bottom Nav Placeholder - if inside layout it persists */}
            <div className="h-20 bg-background-dark/95 backdrop-blur-2xl border-t-2 border-white/10 flex items-center justify-around px-6 shrink-0 z-20">
              <div className="flex flex-col items-center gap-1.5 text-primary">
                <span className="material-symbols-outlined scale-150">dashboard</span>
                <span className="text-xs font-black uppercase">Home</span>
              </div>
              <div className="flex flex-col items-center gap-1.5 text-gray-400">
                <span className="material-symbols-outlined scale-150">calendar_month</span>
                <span className="text-xs font-black uppercase">Calendar</span>
              </div>
              <div className="flex flex-col items-center gap-1.5 text-gray-400">
                <span className="material-symbols-outlined scale-150">volunteer_activism</span>
                <span className="text-xs font-black uppercase">Donate</span>
              </div>
              <div className="flex flex-col items-center gap-1.5 text-gray-400">
                <span className="material-symbols-outlined scale-150">settings</span>
                <span className="text-xs font-black uppercase">Settings</span>
              </div>
            </div>
          </div>

          {/* iOS-like Home Indicator Area */}
          <div className="w-full h-6 bg-background shrink-0 flex justify-center items-start pt-2 z-20">
            <div className="w-1/3 h-1 bg-white/20 rounded-full" />
          </div>
        </div>
      </body>
    </html>
  );
}
